=== CarlosMecha/remote-laboratory-framework/tools/data-tool.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Remote Laboratory Framework -->
<!-- Definición de la estructura de una herramienta de datos en XML. -->
<!-- @author Carlos A. Rodríguez Mecha -->
<!-- @version 0.1 -->
<!ELEMENT tool (out-stream?, attributes, constants, action, resetter)>
	<!ATTLIST tool
				path CDATA #REQUIRED
				data CDATA #FIXED "true"
	>
	<!-- Streams del servicio. -->
	<!ELEMENT out-stream EMPTY>
	<!ELEMENT attributes (name, version, description, admin, role)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT version (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT admin (#PCDATA)>
		<!ELEMENT role (#PCDATA)>
	<!-- Constantes, no pueden ser modificadas. -->
	<!ELEMENT constants (constant*)>
		<!ELEMENT constant (value, description)>
			<!ATTLIST constant 
						name NMTOKEN #REQUIRED
						data-type (int|string|encode|long|double|boolean) "string"
			>
			<!ELEMENT value (#PCDATA)>
	<!-- Acción principal. -->
	<!ELEMENT action (value, description, socket*)>
		<!ATTLIST action
						name NMTOKEN #REQUIRED
						timeout CDATA #REQUIRED
		>
		<!-- Sockets asociados a esta acción. -->
		<!ELEMENT socket EMPTY>
			<!ATTLIST socket
						port CDATA #REQUIRED
						protocol CDATA #REQUIRED
						type (data|media|graph) "data"
						mode CDATA #FIXED "r"
			>
	<!-- Acción especial para reseteo de la herramienta. -->
	<!ELEMENT resetter (#PCDATA)>

=== CarlosMecha/remote-laboratory-framework/tools/windows/RLF_FreeMem/rlffreemem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tool SYSTEM "C:\Users\rodriguezmecha\Documents\My Dropbox\Universidad\Proyecto\rlf\tools\data-tool.dtd" >
<tool path="C:\Users\rodriguezmecha\Documents\My Dropbox\Universidad\Proyecto\rlf\tools\windows\RLF_FreeMem" data="true">
	<out-stream/>
	<attributes>
		<name>RLF FreeMem</name>
		<version>0.1</version>
		<description>Monitorización de memoria disponible en tiempo real en un sistema Windows.</description>
		<admin>carlos</admin>
		<role>0</role>
	</attributes>
	<constants>
		<constant name="time" data-type="int">
			<value>5</value>
			<description>Tiempo en segundos de obtención del dato.</description>
		</constant>
	</constants>
	<action name="mem" timeout="60">
		<value>RLF_FreeMem.exe</value>
		<description>Monitorización constante de la memoria libre.</description>
	</action>
	<resetter>RLF_FreeMem.exe --clear</resetter>
</tool>

=== CarlosMecha/remote-laboratory-framework/tools/linux/RLF_Video/rlfvideo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tool SYSTEM "/home/ramon/RLF/rlf/tools/data-tool.dtd" >
<tool path="/home/ramon/RLF/rlf/tools/linux/RLF_Video" data="true">
	<out-stream/>
	<attributes>
		<name>RLF Video</name>
		<version>0.1</version>
		<description>Streaming de video y sonido. Incluye 3 segundos de delay en el envío. Es necesario utilizar programas externos para poder obtener el flujo de datos.</description>
		<admin>carlos</admin>
		<role>0</role>
	</attributes>
	<constants>
		<constant name="devices" data-type="string">
			<value>v4l2:///dev/video0</value>
			<description>Dispositivos de captura.</description>
		</constant>
		<constant name="http_ip" data-type="string">
			<value>127.0.0.1</value>
			<description>IP del host.</description>
		</constant>
		<constant name="http_port" data-type="int">
			<value>64000</value>
			<description>Puerto de acceso.</description>
		</constant>
		<constant name="user" data-type="string">
			<value>video</value>
			<description>Usuario para la conexión.</description>
		</constant>
		<constant name="pass" data-type="string">
			<value>video</value>
			<description>Contraseña del usuario.</description>
		</constant>
	</constants>
	<action name="http-streaming" timeout="60">
		<value>rlfvideo --http</value>
		<description>Streaming por video mediante el protocolo HMTL. Utilizar un programa como VLC (con recepción de imágenes y sonido por volcado de red) para conectarse al servidor (http://nombre del servidor:puerto/)</description>
		<socket port="64000" protocol="http" type="media" mode="r"/>
	</action>
	<resetter>rlfvideo --clean</resetter>
</tool>
