=== CarlosMecha/remote-laboratory-framework/tools/tool.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Remote Laboratory Framework -->
<!-- Definición de la estructura de la herramienta  en XML. -->
<!-- @author Carlos A. Rodríguez Mecha -->
<!-- @version 0.1 -->
<!ELEMENT tool (in-stream?, out-stream?, attributes, constants, parameters, actions)>
	<!ATTLIST tool 
				path CDATA #REQUIRED
				data CDATA #FIXED "false"
	>
	<!-- Streams del servicio. -->
	<!ELEMENT in-stream EMPTY>
	<!ELEMENT out-stream EMPTY>
	<!ELEMENT attributes (name, version, description, admin, role)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT version (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT admin (#PCDATA)>
		<!ELEMENT role (#PCDATA)>
	<!-- Constantes, no pueden ser modificadas. -->
	<!ELEMENT constants (constant*)>
		<!ELEMENT constant (value, description)>
			<!ATTLIST constant 
						name NMTOKEN #REQUIRED
						data-type (int|string|encode|long|double|boolean) "string"
			>
			<!ELEMENT value (#PCDATA)>
	<!-- Parámetros. Son modificados fuera del tiempo de ejecución. -->
	<!ELEMENT parameters (parameter*)>
		<!ELEMENT parameter (description, default?, max?, min?)>
			<!ATTLIST parameter
						name ID #REQUIRED
						data-type (int|string|encode|long|double|boolean) "string"
			>
			<!ELEMENT default (#PCDATA)>
			<!ELEMENT max (#PCDATA)>
			<!ELEMENT min (#PCDATA)>
	<!-- Acciones de ejecución. -->
	<!ELEMENT actions (action+, resetter)>
		<!ELEMENT action (value, description, socket*, action_parameter*)>
			<!ATTLIST action
						name NMTOKEN #REQUIRED
						timeout CDATA #REQUIRED
			>
			<!-- Sockets asociados a esta acción. -->
			<!ELEMENT socket EMPTY>
				<!ATTLIST socket
						port CDATA #REQUIRED
						protocol CDATA #REQUIRED
						type (data|media|graph) "data"
						mode (r|w|rw) "r"
				>
			<!-- Parámetros asociados a esta acción. -->
			<!ELEMENT action_parameter EMPTY>
				<!ATTLIST action_parameter
						name IDREF #REQUIRED
						type (in|out|inout) "in"
				>
		<!-- Acción especial para reseteo de la herramieta. -->
		<!ELEMENT resetter (#PCDATA)>

=== CarlosMecha/remote-laboratory-framework/tools/linux/RLF_Music/rlfmusic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tool SYSTEM "/home/rodriguezmecha/Universidad/Proyecto/rlf/tools/tool.dtd" >
<tool path="/home/rodriguezmecha/Universidad/Proyecto/rlf/tools/linux/RLF_Music" data="false">
	<in-stream/>
	<out-stream/>
	<attributes>
		<name>RLF Music</name>
		<version>0.1</version>
		<description>Reproductor de música ambiental. Contiene tres canciones, una pop, una chillout y otra rock.</description>
		<admin>carlos</admin>
		<role>0</role>
	</attributes>
	<constants>
	</constants>
	<parameters>
	</parameters>
	<actions>
		<action name="player" timeout="10">
			<value>rlfmusic</value>
			<description>Reproductor de música. Reproduce las canciones bajo petición del usuario.</description>
		</action>
		<resetter>rlfmusic --clear</resetter>
	</actions>
</tool>

=== CarlosMecha/remote-laboratory-framework/tools/windows/RLF_Board/rlfboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tool SYSTEM "C:\Users\rodriguezmecha\Documents\My Dropbox\Universidad\Proyecto\rlf\tools\tool.dtd" >
<tool path="C:\Users\rodriguezmecha\Documents\My Dropbox\Universidad\Proyecto\rlf\tools\windows\RLF_Board" data="false">
	<in-stream/>
	<out-stream/>
	<attributes>
		<name>RLF Board</name>
		<version>0.1</version>
		<description>Controles básicos para la tarjeta Advantech PCI1711. Esta herramienta tiene asociada un servidor FTP para obtener los ficheros generados. Conectar mediante un navegador con el usuario y la contraseña.</description>
		<admin>carlos</admin>
		<role>0</role>
	</attributes>
	<constants>
		<constant name="device" data-type="long">
			<value>0</value>
			<description>Número de dispositivo para realizar las acciones.</description>
		</constant>
		<constant name="channel" data-type="int">
			<value>0</value>
			<description>Canal del dispositivo.</description>
		</constant>
	</constants>
	<parameters>
		<parameter name="volts" data-type="double">
			<description>Voltaje</description>
			<max>10</max>
		</parameter>
	</parameters>
	<actions>
		<action name="Pulse" timeout="6">
			<value>PULSE.exe</value>
			<description>Envía un pulso durante 5 segundos obteniendo los datos de salida del circuito.</description>
			<socket port="64001" protocol="ftp" type="data" mode="r"/>
			<action_parameter name="volts" type="in"/>
		</action>
		<resetter>PULSE.exe --clear</resetter>
	</actions>
</tool>

=== CarlosMecha/remote-laboratory-framework/tools/linux/RLF_DummyTool/rlfdummytool.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tool SYSTEM "/home/rodriguezmecha/Universidad/Proyecto/rlf/tools/tool.dtd" >
<tool path="/home/rodriguezmecha/Universidad/Proyecto/rlf/tools/linux/RLF_DummyTool" data="false">
	<in-stream/>
	<out-stream/>
	<attributes>
		<name>RLF DummyTool</name>
		<version>0.1</version>
		<description>Ejecuciones básicas para realizar pruebas en Linux. Comprende dos acciones que ejecutan operaciones de entrada y salida por teclado y acceso a ficheros locales.</description>
		<admin>carlos</admin>
		<role>0</role>
	</attributes>
	<constants>
	</constants>
	<parameters>
		<parameter name="exit_word" data-type="string">
			<description>Palabra con la que salir del programa.</description>
		</parameter>
		<parameter name="nechos" data-type="int">
			<description>Número de echos realizados.</description>
		</parameter>
	</parameters>
	<actions>
		<action name="echo" timeout="5">
			<value>rlfdummytool --echo</value>
			<description>Repite la entrada por teclado.</description>
			<action_parameter name="exit_word" type="in"/>
			<action_parameter name="nechos" type="out"/>
		</action>
		<action name="cpu-info" timeout="7">
			<value>rlfdummytool --cpu</value>
			<description>Obtiene información básica sobre el sistema (nombre de la máquina y memoria libre) bajo petición del usuario.</description>
		</action>
		<resetter>rlfdummytool --clean</resetter>
	</actions>
	
</tool>
